services:
  - type: web
    name: ndma-auth-backend
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    plan: free
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: PORT
        value: 10000
